services:
  - docker
script: docker-compose run test
notifications:
  slack:
    secure: C7wpVVD3O/1E+IvEd0if5m1AjdXQ9ETJfPhztIqyOskLQVFs0lA0nDMT6Qw+OZkJwAuiTWG3Ouy00f/XcSppP791Nb+1gDfGXQWtIM4g4Sw3FpuPp8DCIBWjx0nwlenrNGrleVaV5j/eT5k60WOE8QB3TGAvteXMdYkhe5jWfjjPHxBGNjhquEoBe3FoztZx31LfwFWsTTwIj1+Jv2Xw7U1Ryz2n5il5MbWl/L+1AILl3n1tTUF9Co/Af43eJTBjt9Txk1OMlnIKLDG+xu8nfiP52Q6as8jS4FYO0S3KLF7lJSyeWjOp2+2AfdFkcu0ZcnDd/Jty6e0SgoqBZz9pipEjBcJcdRcEJG+PWewPljlnXJZFH/1tSPSmRXTr5WOo67kxEw0Irv22CRNWTZhQ41FBQUx/yvvZr7RmBbGhI1dPE0FglzRwEN+/8otEBQwPmQg4BWvDXrOczf986LGNpoHzRFoNzQzMPh0L/FnlsGK6ftsxu3fF7E+YYbe0bhZMc2HjLhCtMbLtWqGEpWoevL48M1dj2W9r0VNpKiO/ArAi9+LKDZxiUQ8g/Hgcm4VLUA1N8F7ailKFXiy9k7ku6TPsBmFJyOBaw3qged6OolJvBrHytX6pogZj5H7LKIT+bfBWgF0teWksxi+/vO9JsByhONZBhu9LifzGmXHji/4=
