version: '3'
services:
  test:
    build: .
    command: 'npm run test:docker:ci'
    depends_on:
      - rabbitmq
    volumes:
      - .:/usr/rss-watcher
      - /usr/rss-watcher/node_modules
  rabbitmq:
    image: 'rabbitmq:3.6.10-alpine'
    ports:
      - '5672'
